name: Continuous Integration
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        bash ./bin/init-local.sh
    - name: Generate Coverage report
      run: |
        source .venv/bin/activate
        pytest --cov=src/ --cov-report=xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true